// **************************************************************
// * Modelo Cliente
// *************************************************************
const { sequelize } = require('../database/config-mssql');
const { DataTypes } = require('sequelize');

const Cliente = sequelize.define('Cliente',{
    idcliente:{
        type:DataTypes.SMALLINT,
        primaryKey:true,
        autoIncrement:true
    },
    idusuarioultimo:{
        type:DataTypes.INTEGER,

    },
    idtipoidentificacion:{
        type:DataTypes.TINYINT,
    },
    idpais:{
        type:DataTypes.SMALLINT
    },
    idestado:{
        type:DataTypes.SMALLINT
    },
    idciudad:{
        type:DataTypes.SMALLINT
    },
    numeroidentificacion:{
     type:DataTypes.STRING(12)
    },
    razonsocial:{
    type:DataTypes.STRING(100)
    },
    nombrecomercial:{
        type:DataTypes.STRING(100)
    },
    dircomercial:{
     type:DataTypes.STRING(200)
    },
    dirfisica:{
     type:DataTypes.STRING(200)
    },
   telefono1:{
    type:DataTypes.STRING(15)
    },
   telefono2:{
    type:DataTypes.STRING(15)
    },
   contacto:{
    type:DataTypes.STRING(50)
    },
   idtipocontribuyente:{
    type:DataTypes.TINYINT
    },
   idmunicipio:{
    type:DataTypes.SMALLINT
    },
   idestatus:{
    type:DataTypes.SMALLINT
    },
   idsector:{
    type:DataTypes.SMALLINT
    },
    codigo:{
        type:DataTypes.STRING(5)
    },
    sexo:{
        type:DataTypes.STRING(1)
    },
    fecnacimiento:{
        type:DataTypes.DATE
    },
    codigorut:{
        type:DataTypes.STRING(12)
    },
    correo:{
        type:DataTypes.STRING(100)
    },
    idcondcomercial:{
        type:DataTypes.TINYINT
    },
    idcondpais:{
        type:DataTypes.TINYINT
    },
    idtipopersona:{
        type:DataTypes.TINYINT
    },
    idzona:{
        type:DataTypes.SMALLINT
    },
    cantidadactivo:{
        type:DataTypes.INTEGER
    },
    idclascli:{
        type:DataTypes.TINYINT
    },
    idcondcredito:{
        type:DataTypes.TINYINT
    },
    saldo:{
        type:DataTypes.DECIMAL(19,4)
    } 
});
module.exports = Cliente;